"""add_pinned_to_conversations

Revision ID: 790bf7a39b4b
Revises: 529ebfcb4126
Create Date: 2026-05-24 14:33:05.806399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '790bf7a39b4b'
down_revision: Union[str, Sequence[str], None] = '529ebfcb4126'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('pinned', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'pinned')
    # ### end Alembic commands ###
